apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world
resources:
- ../../shared
- ../../base

patches:
- target:
    kind: ClusterRoleBinding
    name: service-resolver
  patch: |
    - op: replace
      path: /subjects/0/namespace
      value: hello-world
- target:
    kind: Deployment
    name: service-resolver
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
