apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-resolver
subjects:
  - kind: ServiceAccount
    name: service-resolver
    namespace: service-resolver
roleRef:
  kind: ClusterRole
  name: service-resolver
  apiGroup: rbac.authorization.k8s.io