apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-resolver
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", ]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list"]