apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-resolver
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list",]