apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  namespace: hello-world
spec:
  selector:
    matchLabels:
      app: home
  replicas: 3
  template:
    metadata:
      labels:
        app: home
    spec:
      volumes:
      - name: html
        configMap:
          name: html
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
      nodeSelector:
        name: worker