kind: Cluster
name: local
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  labels:
    name: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,PersistentVolumeClaimResize,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
        service-node-port-range: "80-32767"
- role: worker
  labels:
    name: routing
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      taints:
      - key: routing
        effect: NoSchedule
        value: "true"
- role: worker
  labels:
    name: worker
