apiVersion: v1
kind: Namespace
metadata:
  name: service-resolver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-resolver
  namespace: service-resolver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-resolver
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-resolver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-resolver
subjects:
- kind: ServiceAccount
  name: service-resolver
  namespace: service-resolver
---
apiVersion: v1
kind: Service
metadata:
  name: service-resolver
  namespace: service-resolver
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: service-resolver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-resolver
  namespace: service-resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-resolver
  template:
    metadata:
      labels:
        app: service-resolver
    spec:
      containers:
      - image: ghcr.io/scaleoutllc/service-resolver:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
        name: service-resolver
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
      serviceAccountName: service-resolver
