apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../deploy
- manifests/hello-world/configmap.yml
- manifests/hello-world/deployment.yml
- manifests/hello-world/service.yml
- manifests/hello-world/namespace.yml
patches:
- target:
    kind: Deployment
    name: service-resolver
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: service-resolver:latest
