apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/hello-world/configmap.yml
- manifests/hello-world/deployment.yml
- manifests/hello-world/namespace.yml
- manifests/hello-world/service.yml
